### PR TITLE
Bugfix for the lookup order handling in load() and find()

### PR DESCRIPTION
**Pull request by m0rsch1**
Downward compatible to existing configurations of MultiDBClient

Needs to be tested

### CODE REVIEW

**Comment by m0rsch1** [comment]
#4

**Review by pierrewillenbrockdfki — APPROVED** [review]
This semantically matches what i implemented as a workaround. (I did not reverse the import_interfaces, but instead used iterators on rbegin/rend).

Works as expected.

**Comment by pierrewillenbrockdfki** [comment]
Also of note, there are time windows, where the type pointers from the registry may change content rapidly during the MultiDBClient::find. This can only be observed when the application does multithreaded accesses to type pointers from the same Registry. I did not check if there are any mutexes or similar preventing access in that case. This behavior is _unchanged_ by this pull request.

**Comment by m0rsch1** [comment]
> Also of note, there are time windows, where the type pointers from the registry may change content rapidly during the MultiDBClient::find. This can only be observed when the application does multithreaded accesses to type pointers from the same Registry. I did not check if there are any mutexes or similar preventing access in that case. This behavior is _unchanged_ by this pull request.

No, we have not yet made the interface thread-safe ... in that case we have to introduce a mutex during lookups to prevent inconsistencies. Could you @pierrewillenbrockdfki  open a new issue for that please?

**Comment by m0rsch1** [comment]
> This semantically matches what i implemented as a workaround. (I did not reverse the import_interfaces, but instead used iterators on rbegin/rend).
> 
> Works as expected.

Yeah, that would be faster i guess ... i will change it to rbegin(), rend() before merging.

**Pull request merged**
